version: "3.9"

services:
  crypto-scout-mq:
    image: rabbitmq:4.1.4-management
    container_name: crypto-scout-mq
    hostname: crypto-scout-mq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
      - "5552:5552"   # Stream protocol (required for RabbitMQ streams)
      - "15692:15692" # Prometheus metrics
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
    
    env_file:
      - ./secret/rabbitmq.env
    networks:
      - crypto-scout-bridge
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    stop_grace_period: 1m

networks:
  crypto-scout-bridge:
    name: crypto-scout-bridge
    external: true